### ISSUE TITLE
Fixes/Improvements for pets

### ISSUE THREAD

**Issue by Chris6ix** [datatags/UltraCosmetics#34]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

Important Fixes:

- Prevent Player from transforming a Zombie Villager into a normal villager with a weakness potion and a golden apple
- Prevent Hoglin and Piglin Brute from turning into zombified versions in the overworld
- Fix Magma Cube damaging the player
- Prevent Elder Guardian from giving player mining fatigue

Minor Fixes/Improvements:

- Prevent Player from interacting with certain pets using their breeding items (Such as Pigs using a carrot, Horses using Wheat, Hoglins using a Crimson Fungus etc...) (I think this is just a minor issue as most pets are spawned as a baby version and thus are not able to breed, but still something that needs to be fixed)
- Reduce land speed for Wandering Trader, Evoker, Vindicator, Illusioner
- Increase water speed for Cod, Salmon, Tadpole, Tropical Fish, Turtle and Drowned
- Increase land speed for Skeleton Horse
- Maybe try to get the strider to feel like it's in lava all the time so that it looks better and moves faster
- https://github.com/datatags/UltraCosmetics/pull/22#issuecomment-1237515494 + comment below
- The Elder Guardian is a bit "buggy" when swimming after you (Weird movement, like he's not really willing to follow the player, but is forced to...he kind of tries to turn around all the time)
- Fix burning protection for Zombie, Skeleton etc. bugging (https://imgur.com/a/ELaX3OR)

### What was supposed to happen?

/

### What happened instead?

/

### What version of UltraCosmetics are you using? Do not say 'latest'.

/

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

/

### What plugins do you have installed?

/

### Are there any errors in the console or in logs?

/

### Additional information that could be helpful in fixing the problem

/

**Comment by datatags** [comment]
Apparently some mobs, such as guardians and bats, have hard-coded movement that they do in addition to pathfinders, so there's unfortunately not a great way to prevent them from doing it. So I guess we'll have to decide if the guardian/elder guardian movement is acceptable the way it is or not.

**Comment by Chris6ix** [comment]
If that is not something we can really influence, then I would count that as acceptable movement (As I am also counting no movement at all from the Shulker acceptable 😅)

**Comment by Chris6ix** [comment]
Btw, I just looked at how you fixed the Creeper Flint&Steel bug and if I understand this right, then this would also fix the "Interacting with pets with their breeding items" bug?
![image](https://user-images.githubusercontent.com/65610536/193112526-a821d465-5e92-452a-9f50-237f8ae439ad.png)

**Comment by datatags** [comment]
Yep, it should 🙂 

I'm also working on fixes for burning and for elder guardian giving mining fatigue. An issue I've noticed with that is that there's no way to know which mob the effect is coming from, so we either block mining fatigue coming from legitimate guardians, or we allow mining fatigue from guardian pets. I'm thinking I'll make it a config option so servers can decide. (The same issue exists with the warden.)

**Comment by Chris6ix** [comment]
Oh, okay...wait, so this
![image](https://user-images.githubusercontent.com/65610536/193113866-1d17c5b4-d699-403f-a4e5-496cbc828b0d.png)
cancels all darkness effects from every warden, not just cosmetic ones?

**Comment by datatags** [comment]
Unfortunately yes

**Comment by Chris6ix** [comment]
Oh okay...and is there no way to only execute this code for the entity that has a certain name (e.g. Chris6ix's Warden)?
Or is it maybe possible to work with NBT tags? 
Because It's possible to target only a very specific entity with commands using the entities name or an NBT tag...

**Comment by datatags** [comment]
There isn't, here's all the information that the event provides: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityPotionEffectEvent.html

`getEntity()` is just the entity that the effect is being applied to (the player), `getCause()` is just a generic reason (like `WARDEN`), and the old and new effects give you information on the type of effect and the duration and such, but there's no way to see which entity actually caused the effect.

**Comment by Chris6ix** [comment]
I see. That is very unfortunate, but we can't do anything against it, so I guess the only option is what you said with the config option.

**Comment by Chris6ix** [comment]
As I see right now, the first issue with the Zombie Villager is also fixed by the same fix for the creeper?
Because you can't use the golden apple anymore...

I'm just going to test that real quick and if it actually fixes it, then ill remove them from the list above

**Comment by datatags** [comment]
I've fixed the hoglin and piglin changing, elder guardian giving mining fatigue, the strider shivering, and the burning protection 🙂

**Comment by Chris6ix** [comment]
Alright, updated the issue 😁

**Comment by datatags** [comment]
Apparently the strider isn't fixed, and it seems to be something that's primarily client side despite there being an API for it server side, so there doesn't appear to be anything I can do about it. 😕

**Comment by Chris6ix** [comment]
Oh...that's a bit unfortunate 😕
I guess we just leave the strider how it is then because it still works, it's just slow everywhere where there is no lava (Just like the normal strider)...it's not broken.
